CREATE TABLE contactos (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	cliente VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	num_telemovel VARCHAR(255) NOT NULL,
	mensagem LONGTEXT NOT NULL
);
